name: ci-release

on:
  push:
    branches:
    - release*
    tags:
    - '**'

jobs:
  test-powershell-6-0:
    runs-on: ubuntu-16.04
    container:
      image: theohbrothers/docker-powershell:6.0.2-ubuntu-16.04-git
    steps:
    - uses: actions/checkout@v1
    - name: Display system info (linux)
      run: |
        set -e
        hostname
        whoami
        cat /etc/*release
        lscpu
        free
        df -h
        pwd
    - name: Powershell version
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command '$PSVersionTable'
    - name: Test
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command './test/test.ps1'

  test-powershell-6-1:
    runs-on: ubuntu-16.04
    container:
      image: theohbrothers/docker-powershell:6.1.3-alpine-3.8-git
    steps:
    - uses: actions/checkout@v1
    - name: Display system info (linux)
      run: |
        set -e
        hostname
        whoami
        cat /etc/*release
        # lscpu
        free
        df -h
        pwd
    - name: Powershell version
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command '$PSVersionTable'
    - name: Test
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command './test/test.ps1'

  test-powershell-6-2:
    runs-on: ubuntu-16.04
    container:
      image: theohbrothers/docker-powershell:6.2.4-alpine-3.8-git
    steps:
    - uses: actions/checkout@v1
    - name: Display system info (linux)
      run: |
        set -e
        hostname
        whoami
        cat /etc/*release
        # lscpu
        free
        df -h
        pwd
    - name: Powershell version
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command '$PSVersionTable'
    - name: Test
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command './test/test.ps1'

  test-powershell-7-0:
    runs-on: ubuntu-16.04
    container:
      image: theohbrothers/docker-powershell:7.0.3-alpine-3.9-20200928
    steps:
    - uses: actions/checkout@v1
    - name: Display system info (linux)
      run: |
        set -e
        hostname
        whoami
        cat /etc/*release
        # lscpu
        free
        df -h
        pwd
    - name: Powershell version
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command '$PSVersionTable'
    - name: Test
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command './test/test.ps1'

  test-powershell-7-1:
    runs-on: ubuntu-16.04
    container:
      image: theohbrothers/docker-powershell:7.1.1-alpine-3.11-20210125-git
    steps:
    - uses: actions/checkout@v1
    - name: Display system info (linux)
      run: |
        set -e
        hostname
        whoami
        cat /etc/*release
        # lscpu
        free
        df -h
        pwd
    - name: Powershell version
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command '$PSVersionTable'
    - name: Test
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command './test/test.ps1'

  test-powershell-7-2:
    runs-on: ubuntu-16.04
    container:
      image: theohbrothers/docker-powershell:7.2.0-preview.2-alpine-3.11-20210125-git
    steps:
    - uses: actions/checkout@v1
    - name: Display system info (linux)
      run: |
        set -e
        hostname
        whoami
        cat /etc/*release
        # lscpu
        free
        df -h
        pwd
    - name: Powershell version
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command '$PSVersionTable'
    - name: Test
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command './test/test.ps1'
